server:
  port: 8090
spring:
  #  security:
  #    user:
  #      name: user
  #      password: password
  #      roles: USER

  datasource:
    url: jdbc:mysql://localhost:3306/security-test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: roots
    driver-class-name: com.mysql.jdbc.Driver

  main:
    allow-bean-definition-overriding: true
#  mvc:
#    static-path-pattern: /static/**
#  web:
#    resources:
#      static-locations: classpath://static/