spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_sys?serverTimezone=GMT&characterEncoding=utf-8
    username: root
    password: roots
    # 数据库访问配置, 使用druid数据源
#    type: com.mysql.cj.jdbc.MysqlDataSource
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-aliases-package: com.example.blog.entity.*
  mapper-locations: classpath:mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8084
